project_name: jetstream

release:
  github:
    owner: nats-io
    name: jetstream
  name_template: "Release {{.Tag}}"
  draft: true

changelog:
  skip: true

builds:
  - main: ./nats
    id: nats
    binary: nats
    env:
      - GO111MODULE=on
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm
      - arm64
      - 386
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386

  - main: ./jsm
    id: jsm
    binary: jsm
    env:
      - GO111MODULE=on
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm
      - arm64
      - 386
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386

archives:
  - name_template: "{{.ProjectName}}-{{.Version}}-{{.Os}}-{{.Arch}}{{if .Arm}}{{.Arm}}{{end}}"
    wrap_in_directory: true
    format: zip
    files:
      - README.md
      - LICENSE

dockers:
  - goos: linux
    goarch: amd64
    skip_push: true
    binaries:
      - jsm
      - nats
    image_templates:
      - "synadia/jsm:latest"
      - "synadia/jsm:{{.Version}}"
    extra_files:
      - README.md
      - ngs-server.conf
      - entrypoint.sh

checksum:
  name_template: "SHA256SUMS"
  algorithm: sha256
